/*
* This Java source file was generated by the Gradle 'init' task.
*/
package practice_webapp.foo.bar;

import java.io.IOException;
import java.io.Writer;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
/**
 *
 * HelloWorld
 *
 */
public class MyNameServlet extends HttpServlet {

    /**
     *
     * デフォルト・コンストラクタ
     *
     */

    public MyNameServlet() {

        super();

    }

    @Override

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html; charset=UTF-8");
        request.setCharacterEncoding("UTF-8");
// あ
        Writer out = response.getWriter();

        out.write("<!DOCTYPE html>");
        out.write("<html lang=\"ja\">");
        out.write("<head>");
        out.write("<meta charset=\"UTF-8\">");
        out.write("<title>");
        out.write("MyName");
        out.write("</title>");
        out.write("</head>");
        out.write("<body>");
        out.write("<p>");
        out.write("もりちゃん");
        out.write("</p>");
        out.write("</body>");
        out.write("</html>");

        out.close();

    }

}
